# Generated by Django 4.0.9 on 2023-02-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('link', models.URLField(max_length=1000)),
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
    ]
