# Generated by Django 4.1.7 on 2023-03-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shorturl", "0002_shorturl_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
