# Generated by Django 4.0.9 on 2023-03-06 11:25

from django.db import migrations, models
import django.db.models.deletion
import fileshare.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('name', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zipped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fileshare.models.get_upload_path)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileshare.folder')),
            ],
        ),
    ]
